### ISSUE TITLE
aspect ratio can be broken by pulling on the edge handles 

### ISSUE THREAD

**Issue by sief** [WebSeed/tinycrop#19]
the latest version shows handles on the edges where you can pull only in either x or y direction. If an aspect ratio is set it can be broken by pulling on these handles. The corner handles still seem to respect the aspect ratio, though.

On the demo page I don't see these edge handles, I assume they were introduced in a later version, or is there an option to turn them off?

**Comment by albinmedoc** [comment]
How did you solve this?

**Comment by itconsulting-live** [comment]
The demo page uses tinycrop.min.js which does not have this problem.
